### ISSUE TITLE
gpu: `run-example` not working

### ISSUE THREAD

**Issue by luehmann** [hexops/mach#399]
Running `zig build run-example` within `gpu` fails with:
```
% zig build run-example
./examples/main.zig:217:11: error: expected type '*.gpu.Queue', found '*const .gpu.Queue'
    params.queue.submit(&.{command});
          ^
./examples/main.zig:217:11: note: cast discards const qualifier
    params.queue.submit(&.{command});
```
This was probably introduced with #271

**Comment by alichraghi** [comment]
@slimsag could i mention building/testing `mach/gpu` in #395 ?

**Comment by iddev5** [comment]
This is duplicate of #328 and CI coverage of gpu is also related to #189

**Comment by luehmann** [comment]
@iddev5 indeed. Thanks for pointing it out. Closing as duplicate
